const PLUS = 'PLUS';
const MINUS = 'MINUS';
const MULTYPLICATION = 'MULTYPLICATION';
const DIVIDER = 'DIVIDER';
const FLOAT = 'FLOAT';
const UPDATE = 'UPDATE';
const EQUALS = 'EQUALS';
const ALLCLEAN = 'ALLCLEAN';
const INVERSION = ' INVERSION';
const MEMORY_READ = 'MEMORY_READ';
const MEMORY_CLEAR = 'MEMORY_CLEAR';
const MEMORY_INCREMENT = 'MEMORY_INCREMENT';
const MEMORY_DECREMENT = 'MEMORY_DECREMENT';
const PERCENT = 'PERCENT';

export {
  ALLCLEAN,
  PLUS,
  MINUS,
  UPDATE,
  EQUALS,
  MULTYPLICATION,
  DIVIDER,
  FLOAT,
  INVERSION,
  MEMORY_READ,
  MEMORY_CLEAR,
  MEMORY_INCREMENT,
  MEMORY_DECREMENT,
  PERCENT,
};
